Add a .env_sample file
sendgrid/ruby-http-client pull request #39
Opened 2017-10-27 02:34 UTC by thepriefy

issue #34

2017-10-30 15:46 UTC, mbernier requested changes

2017-10-30 15:46 UTC, mbernier commented on README.md
> +Copy ```.env_sample``` and change its name to ```.env.```
@thepriefy please make the same change here that you made on the other repos - remove one of the sections here.

2017-10-31 02:31 UTC, mbernier approved these changes

2017-10-31 02:31 UTC, merged

2017-10-31 02:31 UTC, thinkingserious commented
Hello @thepriefy,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/announcing-hacktoberfest-2017">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX