Add Code Review to Contributing.md #63
sendgrid/ruby-http-client pull request #64
Opened 2017-10-31 19:50 UTC by derekneuland

# Fixes #63 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

2017-10-31 19:50 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/not_signed)](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=64) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=64) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/ruby-http-client?pullRequest=64) it.</sub>

2018-10-19 19:10 UTC, kplimack approved these changes

2018-10-19 19:11 UTC, kplimack requested changes

2018-10-19 19:11 UTC, kplimack commented on CONTRIBUTING.md
> +## Code Reviews<a name="code-reviews"></a>
you do not need to insert an HTML anchor tag, github makes anchors automatically for every heading you make, inserting dashes in lieu of spaces

2018-10-19 19:12 UTC, kplimack commented on CONTRIBUTING.md
> +## Code Reviews<a name="code-reviews"></a>
the link would look like
```
[Code Review](#code-reviews)
```

2020-02-21 17:15 UTC, childish-sambino commented
Duplicates #100

2020-02-21 17:15 UTC, closed without merging