Add USAGE.md
sendgrid/ruby-http-client pull request #72
Opened 2018-10-01 03:01 UTC by ProZsolt

# Fixes #44

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

2018-10-02 15:28 UTC, kplimack requested changes
@ProZsolt thank you for your contribution!  I left a couple small requests for minor updates.

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
add `ruby` code formatter
i.e.
```
 ```ruby
 <code>
 ....
```

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +<a name="put"></a>
markdown automatically generates anchors to each header, you can remove all the html tags
`[create an anchor](#anchors-in-markdown)`

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +<a name="patch"></a>
markdown automatically generates anchors to each header, you can remove all the html tags

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
add ruby formatter

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +<a name="post"></a>
markdown automatically generates anchors to each header, you can remove all the html tags

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
ruby formatter

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
ruby formatter

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +<a name="delete"></a>
markdown automatically generates anchors to each header, you can remove all the html tags

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +<a name="get"></a>
markdown automatically generates anchors to each header, you can remove all the html tags

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
ruby formatter

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
ruby formatter

2018-10-02 15:28 UTC, kplimack commented on USAGE.md
> +```
ruby formatter

2018-10-02 17:25 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/signed)](https://cla.sendgrid.com/sendgrid/ruby-http-client?pullRequest=72) <br/>All committers have signed the CLA.

2018-10-02 17:27 UTC, kplimack approved these changes

2018-10-04 00:54 UTC, thinkingserious commented
Hello @ProZsolt,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

2018-10-04 00:54 UTC, merged

2018-10-25 23:36 UTC, thinkingserious commented
Hello @ProZsolt,<br /><br/>Thanks again for the PR!<br /><br />                                         We noticed that you have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold.<br /><br />                                         Also, please be sure that you have officially registered <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid DX

2018-10-31 16:37 UTC, thinkingserious commented
Hello @ProZsolt,<br /><br/>Thanks again for the PR!<br /><br />                                         You have earned 3 out of the 5 points needed to receive glorious SendGrid Hacktoberfest swag.<br /><br />                                         Please take a moment to checkout <a href="https://dx.sendgrid.com/hacktoberfest/issues">this link</a> to find more issues to get you past the required threshold or to simply continue the celebration.<br /><br />                                         Also, <strong>please be sure you have officially registered with us <a href="https://dx.sendgrid.com/hacktoberfest/join">here</a> by November 1, 2018</strong> to qualify.<br /><br />                                         If you have any questions you can email us at <a href="mailto:dx+hacktoberfest2018@sendgrid.com">dx+hacktoberfest2018@sendgrid.com</a>.<br /><br />                                         Thank you and Happy Hacktobering!<br /><br />                                         Team SendGrid

2018-10-31 19:54 UTC, ProZsolt commented
Sadly, I will miss out on this :( I would be happy to contribute more, but
I'm currently on a road trip around New Zealand. Where I barely have
internet or electricity. Last year it was one merged PR. This year it
wasn't mentioned it changed, that's why I did my PRs in the begining of
October. I also got confirmation when my other two PRs was merged.
Please next time make sure if something changes let people know immediately
and not it the end when they only have few days to react.
It's a bit of let down, but see you guys next year.